In [1]:
%matplotlib inline
%env KERAS_BACKEND=tensorflow
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.image as mpimg
# from ipywidgets import interact
from ipywidgets import interact_manual

# import sympy as sym
# from sympy import S,N
# import locale
# from sklearn.linear_model import LinearRegression

# from keras.utils import np_utils #one hot encoding
# from keras.models import Sequential #神經網路的框架keras.models
from keras.layers import Dense, Activation
from keras.layers import Flatten # 將資料展平
from keras.layers import Conv2D, MaxPool2D, MaxPooling2D
from keras.optimizers import SGD, Adadelta
# from keras.models import model_from_json
# from keras.datasets import mnist # mnist內 包含手寫測試資料

#for Functional API
from keras.models import Model
from keras.layers import Input
from keras.layers import concatenate, add
#for Functional API transfer learning

from keras.layers.core import Lambda
from keras import backend as K

# from keras.preprocessing.image import ImageDataGenerator
# from keras.layers import Dropout

# import matplotlib.image as mpimg #import image file
# from sklearn.model_selection import train_test_split

env: KERAS_BACKEND=tensorflow


Using TensorFlow backend.


In [4]:
x = Input(shape = (None, None, 3), name='x')
z = Conv2D(4,(10, 10), padding = 'same', activation = 'relu', name='c1')(x)
z = MaxPool2D(pool_size = (2, 2), name='m1')(z)
z = Conv2D(8,(8, 8), padding = 'same', activation = 'relu', name='c2')(z)
z = MaxPool2D(pool_size = (2, 2), name='m2')(z)
# z = Conv2D(8,(2, 2), padding = 'same', activation = 'relu', name='c3')(z)
# z = MaxPool2D(pool_size = (2, 2), name='m3')(z)
z = Conv2D(16,(4, 4), padding = 'same', activation = 'relu', name='c4')(z)
z = MaxPool2D(pool_size = (2, 2), name='m4')(z)
# z = Conv2D(32,(2, 2), padding = 'same', activation = 'relu', name='c5')(z)
# z = MaxPool2D(pool_size = (2, 2), name='m5')(z)
# z = Conv2D(16,(2, 2), padding = 'same', activation = 'relu', name='c6')(z)
# z = MaxPool2D(pool_size = (2, 2), name='m6')(z)
# z = Conv2D(8,(2, 2), padding = 'same', activation = 'relu', name='c7')(z)
# z = MaxPool2D(pool_size = (2, 2), name='m7')(z)
z = Conv2D(8,(2, 2), padding = 'same', activation = 'relu', name='c8')(z)
z = MaxPool2D(pool_size = (2, 2), name='m8')(z)
y = Conv2D(4,(1, 1), padding = 'same', activation = 'softmax', name='y')(z)
# Conv2D(..,(1, 1)..可想成是變動 input_dim 的 Dense層 
model = Model(x, y)

model.compile(loss='categorical_crossentropy', optimizer=Adadelta(), metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
x (InputLayer)               (None, None, None, 3)     0         
_________________________________________________________________
c1 (Conv2D)                  (None, None, None, 4)     1204      
_________________________________________________________________
m1 (MaxPooling2D)            (None, None, None, 4)     0         
_________________________________________________________________
c2 (Conv2D)                  (None, None, None, 8)     2056      
_________________________________________________________________
m2 (MaxPooling2D)            (None, None, None, 8)     0         
_________________________________________________________________
c4 (Conv2D)                  (None, None, None, 16)    2064      
_________________________________________________________________
m4 (MaxPooling2D)            (None, None, None, 16)    0         
__________

In [5]:
for idx in range(1,7):
    img = mpimg.imread(F"image_test/test ({idx}).png")
    img = img[:,:,0:3]
    imgs = img.reshape(1,*img.shape)
    predict = model.predict(imgs)
    print('\n',predict[0])
#     print(predict.shape)


 [[[0.25908515 0.24692355 0.2767561  0.21723515]
  [0.25700065 0.25039825 0.27026942 0.22233167]
  [0.2445995  0.25383618 0.2829804  0.21858388]]

 [[0.28400254 0.24606533 0.30233887 0.16759321]
  [0.2840219  0.23247199 0.3164772  0.16702881]
  [0.21679573 0.27671152 0.34471795 0.16177475]]

 [[0.33335227 0.21120487 0.30114597 0.15429688]
  [0.33326173 0.20948923 0.29842737 0.15882167]
  [0.24167177 0.2644988  0.35306337 0.14076604]]]

 [[[0.2988988  0.23032184 0.27014017 0.20063916]
  [0.297962   0.22970201 0.26923227 0.20310372]
  [0.28010133 0.23439965 0.27446365 0.21103542]]

 [[0.28619185 0.23840693 0.2715595  0.20384167]
  [0.28994507 0.23767911 0.26172915 0.21064672]
  [0.273386   0.24802831 0.26862714 0.20995858]]

 [[0.2912907  0.23354284 0.28475255 0.19041395]
  [0.2849583  0.2372537  0.28416634 0.19362174]
  [0.25618076 0.25674593 0.2866379  0.20043536]]]

 [[[0.2609917  0.2568414  0.35824773 0.12391917]]]

 [[[0.2497941  0.27558336 0.31684974 0.15777281]]]

 [[[0.29539475 