In [1]:
%matplotlib inline
# %matplotlib widget # 跟圖互動，可以用點選圖片中的某位置觸發程式
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
# from random import shuffle
# from matplotlib.widgets import Cursor, Button
from ipywidgets import interact, IntSlider, Button
from ipywidgets import interact_manual
# import IPython.display as ipd # play audio
# import networkx as nx # draw graph vertex & edge
# import pydub # audio
# from numpy.fft import fft, ifft, irfft, rfft # fourier transform
# import sympy as sym
# from sympy import S,N
# import locale # 資料處理 轉換數字格式

In [2]:
def Reduced_Row_Echelon_Form(A):
    A = A.copy()
    A = A.astype('float64')
    assert len(A.shape) == 2, "The input is not a matrix!"
    
    # return the Row Echelon Form of A and print the process step by step.
    def Row_Echelon(A, Output_matrix, idx_r = 0, idx_c = 0):
        A = A.copy()
        
        # A_var starts from the position (idx_r, idx_c) in Output_matrix_var
        def printA(A_var, Output_matrix_var, idx_r, idx_c):
            Output_matrix_var[idx_r:, idx_c:] = A_var
            Output_matrix = Output_matrix_var.copy()
            if not np.all(A_var == 0., axis = 0)[0]:
                print(Output_matrix, "\n")
        
        if idx_r == 0 and idx_c == 0:
            print("A = \n", A, "\n\nRow_Echelon~~~")
        if np.all(A == 0., axis = 0)[0]:
            if A.shape[0] == 1:
                return A
            A[:, 1:] = Row_Echelon(A[:, 1:], Output_matrix, idx_r = idx_r, idx_c = idx_c + 1)
            return A

        # find the row index of first non-zero term
        idx = 0
        for i in range(A.shape[0]):
            if A[i, 0] != 0:
                idx = i
                break

        # interchange two row
        if idx > 0:
            temp = A[0].copy()
            A[0] = A[idx]
            A[idx] = temp
            printA(A, Output_matrix, 0, 0)

        # modify the leading number to 1
        leading_number = A[0, 0]
        A[0] = A[0] / A[0, 0]
        if leading_number != 1.:
            printA(A, Output_matrix, idx_r, idx_c)

        for i in range(1, A.shape[0]):
            if A[i, 0] != 0:
                A[i] -= A[0] * A[i, 0]
                printA(A, Output_matrix, idx_r, idx_c)
        if A.shape[0] == 1 or A.shape[1] == 1:
            return A
        A[1:, 1:] = Row_Echelon(A[1:, 1:], Output_matrix, idx_r = idx_r + 1, idx_c = idx_c + 1)
        return A
    Row_Echelon_Form = Row_Echelon(A, A)
    print("The Row Echelon Form of A is :")
    print(Row_Echelon_Form, "\n\n")
    
    # return the Reduce Row Echelon Form of A and print the process step by step.
    def Reduced(A):
        if np.all(A == 0.):
            return A
        print("Reduced_Row_Echelon~~~")
        for r in range(A.shape[0])[::-1]:
            if np.all(A[r] == 0.):
                continue
            temp = A[r].copy()

            # find the column index of leading's 1
            nonzero_idx_c = 0
            for j in range(A.shape[1]):
                if temp[j] != 0:
                    nonzero_idx_c = j
                    break

            for i in range(r)[::-1]:
                if A[i, nonzero_idx_c] != 0:
                    A[i] -= temp * A[i, nonzero_idx_c]
                    print(A, "\n")
        return A
    Reduced_Row_Echelon = Reduced(Row_Echelon_Form)
    print("The Reduced Row Echelon Form of A is :")
    print(Reduced_Row_Echelon, "\n\n")
    return Row_Echelon, Reduced_Row_Echelon

In [3]:
A = np.array([[0, 5, 35, 10, 5], 
              [1, 4, 1, 3, 0], 
              [3, 14, 17, 16, 5], 
              [1, 7, 22, 11, 5]])

Row_Echelon, Reduced_Row_Echelon = Reduced_Row_Echelon_Form(A)


A = 
 [[ 0.  5. 35. 10.  5.]
 [ 1.  4.  1.  3.  0.]
 [ 3. 14. 17. 16.  5.]
 [ 1.  7. 22. 11.  5.]] 

Row_Echelon~~~
[[ 1.  4.  1.  3.  0.]
 [ 0.  5. 35. 10.  5.]
 [ 3. 14. 17. 16.  5.]
 [ 1.  7. 22. 11.  5.]] 

[[ 1.  4.  1.  3.  0.]
 [ 0.  5. 35. 10.  5.]
 [ 0.  2. 14.  7.  5.]
 [ 1.  7. 22. 11.  5.]] 

[[ 1.  4.  1.  3.  0.]
 [ 0.  5. 35. 10.  5.]
 [ 0.  2. 14.  7.  5.]
 [ 0.  3. 21.  8.  5.]] 

[[ 1.  4.  1.  3.  0.]
 [ 0.  1.  7.  2.  1.]
 [ 0.  2. 14.  7.  5.]
 [ 0.  3. 21.  8.  5.]] 

[[ 1.  4.  1.  3.  0.]
 [ 0.  1.  7.  2.  1.]
 [ 0.  0.  0.  3.  3.]
 [ 0.  3. 21.  8.  5.]] 

[[1. 4. 1. 3. 0.]
 [0. 1. 7. 2. 1.]
 [0. 0. 0. 3. 3.]
 [0. 0. 0. 2. 2.]] 

[[1. 4. 1. 3. 0.]
 [0. 1. 7. 2. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 2. 2.]] 

[[1. 4. 1. 3. 0.]
 [0. 1. 7. 2. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]] 

The Row Echelon Form of A is :
[[1. 4. 1. 3. 0.]
 [0. 1. 7. 2. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]] 


Reduced_Row_Echelon~~~
[[ 1.  4.  1.  3.  0.]
 [ 0.  1.  7.  0. -1.]
 [ 0.  0

In [4]:
A = np.array([[0, 5, 35, 1, 0, 0], 
              [1, 4, 1, 0, 1, 0], 
              [3, 14, 19, 0, 0, 1]])

Row_Echelon, Reduced_Row_Echelon = Reduced_Row_Echelon_Form(A)

A = 
 [[ 0.  5. 35.  1.  0.  0.]
 [ 1.  4.  1.  0.  1.  0.]
 [ 3. 14. 19.  0.  0.  1.]] 

Row_Echelon~~~
[[ 1.  4.  1.  0.  1.  0.]
 [ 0.  5. 35.  1.  0.  0.]
 [ 3. 14. 19.  0.  0.  1.]] 

[[ 1.  4.  1.  0.  1.  0.]
 [ 0.  5. 35.  1.  0.  0.]
 [ 0.  2. 16.  0. -3.  1.]] 

[[ 1.   4.   1.   0.   1.   0. ]
 [ 0.   1.   7.   0.2  0.   0. ]
 [ 0.   2.  16.   0.  -3.   1. ]] 

[[ 1.   4.   1.   0.   1.   0. ]
 [ 0.   1.   7.   0.2  0.   0. ]
 [ 0.   0.   2.  -0.4 -3.   1. ]] 

[[ 1.   4.   1.   0.   1.   0. ]
 [ 0.   1.   7.   0.2  0.   0. ]
 [ 0.   0.   1.  -0.2 -1.5  0.5]] 

The Row Echelon Form of A is :
[[ 1.   4.   1.   0.   1.   0. ]
 [ 0.   1.   7.   0.2  0.   0. ]
 [ 0.   0.   1.  -0.2 -1.5  0.5]] 


Reduced_Row_Echelon~~~
[[ 1.   4.   1.   0.   1.   0. ]
 [ 0.   1.   0.   1.6 10.5 -3.5]
 [ 0.   0.   1.  -0.2 -1.5  0.5]] 

[[ 1.   4.   0.   0.2  2.5 -0.5]
 [ 0.   1.   0.   1.6 10.5 -3.5]
 [ 0.   0.   1.  -0.2 -1.5  0.5]] 

[[  1.    0.    0.   -6.2 -39.5  13.5]
 [  0.    1.    0.   